# Generated by Django 3.1.3 on 2020-11-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201128_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
