# Generated by Django 3.1.3 on 2020-11-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201128_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoativo',
            name='Volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
