# Generated by Django 3.1.3 on 2020-11-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201128_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoativo',
            name='data',
            field=models.CharField(max_length=15),
        ),
    ]
