# Generated by Django 3.1.3 on 2020-11-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201129_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoativo',
            name='data',
            field=models.DateField(),
        ),
    ]
